spring:
  cloud:
    gateway:
      routes:
        - id: customer-service
          uri: http://localhost:8001
          predicates:
            - Path=/customers/**
        - id: inventory-service
          uri: http://localhost:8002
          predicates:
            - Path=/products/**